[custom.all.async-dom]
type   = "local"
path   = "."
ipkg   = "async-dom.ipkg"

[custom.all.async-dom-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.css]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-css"
commit = "latest:main"
ipkg   = "css.ipkg"

[custom.all.async]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async"
commit = "latest:refactor_loggable"
ipkg   = "async.ipkg"

[custom.all.streams]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-streams"
commit = "latest:refactor_loggable"
ipkg   = "streams.ipkg"
